apiVersion: v1
kind: Namespace
metadata:
  name: core-dns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredns
  namespace: core-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coredns
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  - pods
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coredns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coredns
subjects:
- kind: ServiceAccount
  name: coredns
  namespace: core-dns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: core-dns
data:
  Corefile: |
    .:53 {
        errors
        health
        file /etc/coredns/local.zone local.zone
        prometheus :9153
        cache 30
        loop
        reload
        loadbalance
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: core-dns
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: coredns
  template:
    metadata:
      labels:
        k8s-app: coredns
    spec:
      serviceAccountName: coredns
      containers:
      - name: coredns
        image: k8s.gcr.io/coredns/coredns:v1.8.0
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: coredns
          items:
          - key: Corefile
            path: Corefile
      - name: local-zone
        configMap:
          name: local-zone
          items:
          - key: local.zone
            path: local.zone
